blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:pk>", views.post_detail, name="post_detail"),
    path("customers/", views.customer_list, name="customer_list"),
    path("customers/new/", views.customer_create, name="customer_create"),
    path("sellers/", views.seller_list, name="seller_list"),
    path("sellers/new/", views.seller_create, name="seller_create"),
    path("products/", views.product_list, name="product_list"),
    path("products/new/", views.product_create, name="product_create"),
    path("sales/", views.sale_list, name="sale_list"),
    path("sales/new/", views.sale_create, name="sale_create"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/", include("blog.urls"))
]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} - {self.content}"

class Customer(models.Model):
    first_name = models.CharField('First Name', max_length=200)
    last_name = models.CharField('Last Name', max_length=200)
    phone = models.CharField('Phone',max_length=200)
    email = models.EmailField("Email", unique=True)

    class Meta:
        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Seller(models.Model):
    class Position(models.TextChoices):
        SELLER = 'SELLER', 'Seller'
        HEAD_SELLER = 'HEAD_SELLER', 'Head Seller'
        MANAGER = 'MANAGER', 'Manager of sellers'

    first_name = models.CharField('First Name', max_length=200)
    last_name = models.CharField('Last Name', max_length=200)
    phone = models.CharField('Phone', max_length=200)
    email = models.EmailField("Email", unique=True)
    hire_date = models.DateField("Hire Date", auto_now_add=True)
    position = models.CharField('Position', max_length=20, choices=Position.choices, default=Position.SELLER)
    class Meta:
        verbose_name = 'Seller'
        verbose_name_plural = 'Sellers'

    def __str__(self):
        return f"{self.first_name} {self.last_name} "

class Product(models.Model):
    name = models.CharField('Title', max_length=200)
    description = models.TextField()
    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return f"{self.name}"

class Sale(models.Model):
    customer = models.ForeignKey(Customer,verbose_name='customer', on_delete=models.CASCADE,related_name='sales')
    seller = models.ForeignKey(Seller,verbose_name='seller', on_delete=models.PROTECT,related_name='sales')
    product = models.ForeignKey(Product, verbose_name='product', on_delete=models.PROTECT, related_name='sales')
    sale_date = models.DateField('date', auto_now_add=True)
    amount = models.DecimalField('Amount', max_digits=10, decimal_places=2)
    class Meta:
        verbose_name = 'Sale'
        verbose_name_plural = 'Sales'
    def __str__(self):
        return f"{self.sale_date} {self.product} -> {self.customer}"

blog/forms.py
from django import forms
from .models import Customer, Seller, Product, Sale

class PostForm(forms.Form):
    title = forms.CharField(label="Title", max_length=200)
    content = forms.CharField(label="Content", widget=forms.Textarea)

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = "__all__"

class SellerForm(forms.ModelForm):
    class Meta:
        model = Seller
        fields = "__all__"

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = "__all__"

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Customer, Seller, Product, Sale
from .forms import PostForm, CustomerForm, SellerForm, ProductForm, SaleForm
def post_list(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            Post.objects.create(
                title=form.cleaned_data["title"],
                content=form.cleaned_data["content"],
                is_published=False,
            )
            return redirect("blog:post_list")
    else:
        form = PostForm()
    posts = Post.objects.filter(is_published=True).order_by("-create_at")
    context = {"posts": posts, "form": form}
    return render(request, "blog/post_list.html", context)

def post_detail(request, pk: int):
    post = get_object_or_404(Post, pk=pk, is_published=True)
    context = {"post": post}
    return render(request, "blog/post_detail.html", context)

def customer_list(request):
    customers = Customer.objects.all()
    return render(request, "blog/customer_list.html", {"customers": customers})

def customer_create(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("blog:customer_list")
    else:
        form = CustomerForm()
    return render(request, "blog/customer_form.html", {"form": form})

def seller_list(request):
    sellers = Seller.objects.all()
    return render(request, "blog/seller_list.html", {"sellers": sellers})

def seller_create(request):
    if request.method == "POST":
        form = SellerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("blog:seller_list")
    else:
        form = SellerForm()
    return render(request, "blog/seller_form.html", {"form": form})

def product_list(request):
    products = Product.objects.all()
    return render(request, "blog/product_list.html", {"products": products})

def product_create(request):
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("blog:product_list")
    else:
        form = ProductForm()
    return render(request, "blog/product_form.html", {"form": form})

def sale_list(request):
    sales = Sale.objects.all()
    return render(request, "blog/sale_list.html", {"sales": sales})

def sale_create(request):
    if request.method == "POST":
        form = SaleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("blog:sale_list")
    else:
        form = SaleForm()
    return render(request, "blog/sale_form.html", {"form": form})

blog/templates/blog/customer_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New customer</title>
</head>
<body>
    <h1>New customer</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
<a href="{% url 'customer_list' %}">← Back </a>
</body>
</html>

blog/templates/blog/customer_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Customer</title>
</head>
<body>
<h1>Customers</h1>

<a href="{% url 'blog:customer_create' %}">Create customer</a>
<table border="1">
    <tr>
        <th>Name</th>
        <th>Surname</th>
        <th>Phone</th>
        <th>Email</th>
    </tr>
    {% for customer in customers %}
    <tr>
        <td>{{ customer.first_name }}</td>
        <td>{{ customer.last_name }}</td>
        <td>{{ customer.phone }}</td>
        <td>{{ customer.email }}</td>
    </tr>
    {% empty %}
        <tr><td colspan="4">No customers</td> </tr>
    {% endfor %}
</table>

</body>
</html>

blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="utf-8">
    <title>{{ post.title }} — Блог</title>
</head>
<body>
    <h1>{{ post.title }}</h1>

    <p><small>Створено: {{ post.created_at }} | Оновлено: {{ post.updated_at }}</small></p>

    <article>
        <p>{{ post.content|linebreaks }}</p>
    </article>

    <p>
        <a href="{% url 'blog:post_list' %}">← Повернутися до списку постів</a>
    </p>
</body>
</html>

blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="utf-8">
    <title>Блог — список постів</title>
</head>
<body>
    <h1>Блог</h1>

    <form method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Save</button>
    </form>

    {% if posts %}
        <ul>
            {% for post in posts %}
                <li>
                    <h2>
                        <a href="{% url 'blog:post_detail' post.pk %}">
                            {{ post.title }}
                            {{ post }}
                        </a>
                    </h2>
                    <p><small>Створено: {{ post.create_at }}</small></p>
                    <p>
                        {{ post.content|truncatechars:150 }}
                    </p>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Поки що немає опублікованих постів.</p>
    {% endif %}
</body>
</html>